# Generated by Django 3.1.6 on 2021-02-23 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_moviemod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieMod',
        ),
    ]
