# Generated by Django 3.1.6 on 2021-03-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_delete_moviemod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_release_year', models.TextField()),
                ('movie_format', models.CharField(max_length=20)),
                ('movie_genre', models.CharField(max_length=20)),
                ('movie_want', models.CharField(max_length=2)),
                ('movie_own', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('director_id', models.AutoField(primary_key=True, serialize=False)),
                ('director_first_name', models.CharField(max_length=40)),
                ('director_last_name', models.CharField(max_length=40)),
                ('director_dob', models.DateField(blank=True, null=True)),
                ('director_country', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'directors',
                'managed': True,
            },
        ),
    ]
