# Generated by Django 3.1.6 on 2021-03-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_directors_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_release_year', models.TextField()),
                ('movie_format', models.CharField(max_length=20)),
                ('movie_genre', models.CharField(max_length=20)),
                ('movie_want', models.CharField(max_length=2)),
                ('movie_own', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
        migrations.RenameModel(
            old_name='Directors',
            new_name='Director',
        ),
    ]
