# Generated by Django 3.1.6 on 2021-03-01 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_database', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Directors',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
